### ISSUE TITLE
Page build failed when deploy on GitHub

### ISSUE THREAD

**Issue by HHONG-WM** [yizeng/jekyll-theme-simple-texture#20]
Hi,

Thanks for providing this awesome theme. I really like it. 

However, an error message shows when I upload `starter-kit` to GitHub.
```
The page build failed for the `master` branch with the following error:
A file was included in `blog/tags/index.html` that is a symlink or does not exist in your `_includes` directory. For more information, see https://help.github.com/articles/page-build-failed-file-is-a-symlink/.
```
My repository is [here](https://github.com/HHONG-WM/HHONG-WM.GITHUB.IO/blob/master/blog/tags/index.html).

I was wondering if you would like to take some time and let me know what is the right way to fix this?

Thanks,
HONG

**Comment by yizeng** [comment]
@HHONG-WM Sure thing. I'll look into this as soon as I can.

**Comment by yizeng** [comment]
@HHONG-WM The files were the same as the original long time ago. Not sure what's happening.

I need time to dig further.

**Comment by HHONG-WM** [comment]
@yizeng Thank you for your help.

**Comment by blindjesse** [comment]
I ran into this same problem. You probably just need to change this line in `_config.yml`

`theme: jekyll-theme-simple-texture`

to 

`remote_theme: yizeng/jekyll-theme-simple-texture`.

This is because this theme is not in the short ["officially" supported list](https://pages.github.com/themes/), and we need the workaround described [here](https://blog.github.com/2017-11-29-use-any-theme-with-github-pages/).
